//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BellatorTabernae.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CombatStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CombatStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BellatorTabernae.Properties.CombatStrings", typeof(CombatStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; är dock inte färdig utan riktar ännu en attack mot &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; som träffar! &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; skadas {2}!&lt;/div&gt;.
        /// </summary>
        internal static string AttackCounter1 {
            get {
                return ResourceManager.GetString("AttackCounter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; ger sig inte så lätt utan attackerar &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; på nytt och träffar! &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; skadas {2}!&lt;/div&gt;.
        /// </summary>
        internal static string AttackCounter2 {
            get {
                return ResourceManager.GetString("AttackCounter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men det verkar som om &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; planerade det här från början när en ny attack direkt kommer mot &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt;s håll och träffar! &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; skadas {2}!&lt;/div&gt;.
        /// </summary>
        internal static string AttackCounter3 {
            get {
                return ResourceManager.GetString("AttackCounter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; tappar tillfälligt tankeförmågan efter attacken och är inte alls med när &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; attackerar på nytt och träffar! &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; skadas {2}!&lt;/div&gt;.
        /// </summary>
        internal static string AttackCounter4 {
            get {
                return ResourceManager.GetString("AttackCounter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to och träffar! &lt;span class=&quot;defender&quot;&gt;{0}&lt;/span&gt; skadas {1}!&lt;/div&gt;.
        /// </summary>
        internal static string AttackHit {
            get {
                return ResourceManager.GetString("AttackHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; är otroligt klumpig och missar attacken! .
        /// </summary>
        internal static string AttackMiss1 {
            get {
                return ResourceManager.GetString("AttackMiss1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; missar! .
        /// </summary>
        internal static string AttackMiss2 {
            get {
                return ResourceManager.GetString("AttackMiss2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; trampar snett och missar! .
        /// </summary>
        internal static string AttackMiss3 {
            get {
                return ResourceManager.GetString("AttackMiss3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; blir distraherad och missar attacken! .
        /// </summary>
        internal static string AttackMiss4 {
            get {
                return ResourceManager.GetString("AttackMiss4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;defender&quot;&gt;{0}&lt;/span&gt; lyckas blockera attacken! .
        /// </summary>
        internal static string BlockAttack1 {
            get {
                return ResourceManager.GetString("BlockAttack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;defender&quot;&gt;{0}&lt;/span&gt; blockerar attacken! .
        /// </summary>
        internal static string BlockAttack2 {
            get {
                return ResourceManager.GetString("BlockAttack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;defender&quot;&gt;{0}&lt;/span&gt; är beredd på attacken och lyckas med enkelhet blockera den! .
        /// </summary>
        internal static string BlockAttack3 {
            get {
                return ResourceManager.GetString("BlockAttack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;defender&quot;&gt;{0}&lt;/span&gt; hade tur och lyckas precis blockera attacken! .
        /// </summary>
        internal static string BlockAttack4 {
            get {
                return ResourceManager.GetString("BlockAttack4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;deadString&quot;&gt;Tyvärr så avled {0} av sina skador.&lt;/span&gt;.
        /// </summary>
        internal static string DeadString {
            get {
                return ResourceManager.GetString("DeadString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; tar tillfället i akt och riktar en motattack mot &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; och träffar! &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; skadas {2}!&lt;/div&gt;.
        /// </summary>
        internal static string DefenderCounter1 {
            get {
                return ResourceManager.GetString("DefenderCounter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; ser sin chans och attackerar den oförberedde &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt;. Attacken träffar! &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; skadas {2}!&lt;/div&gt;.
        /// </summary>
        internal static string DefenderCounter2 {
            get {
                return ResourceManager.GetString("DefenderCounter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; hittar snabbt balansen och gör en motattack mot &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; innan denne hinner reagera, och träffar! &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; skadas {2}!&lt;/div&gt;.
        /// </summary>
        internal static string DefenderCounter3 {
            get {
                return ResourceManager.GetString("DefenderCounter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innan &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; hinner förstå vad det är som händer har &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; tagit tillfället i akt och gjort en motattack, som träffar! &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; skadas {2}!&lt;/div&gt;.
        /// </summary>
        internal static string DefenderCounter4 {
            get {
                return ResourceManager.GetString("DefenderCounter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;endresult&quot;&gt;Oj! Samtliga kombattanter gav upp striden samtidigt! Det ser ut som om den här striden slutar oavgjort!&lt;/div&gt;.
        /// </summary>
        internal static string DrawString {
            get {
                return ResourceManager.GetString("DrawString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;defender&quot;&gt;{0}&lt;/span&gt; lyckas undvika attacken! .
        /// </summary>
        internal static string EvadeAttack1 {
            get {
                return ResourceManager.GetString("EvadeAttack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;defender&quot;&gt;{0}&lt;/span&gt; är tillräckligt snabb på foten för att komma utom räckhåll för attacken! .
        /// </summary>
        internal static string EvadeAttack2 {
            get {
                return ResourceManager.GetString("EvadeAttack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men för &lt;span class=&quot;defender&quot;&gt;{0}&lt;/span&gt; är det ingen konst att akta sig för attacken! .
        /// </summary>
        internal static string EvadeAttack3 {
            get {
                return ResourceManager.GetString("EvadeAttack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to men &lt;span class=&quot;defender&quot;&gt;{0}&lt;/span&gt; lyckas precis på håret undvika attacken! .
        /// </summary>
        internal static string EvadeAttack4 {
            get {
                return ResourceManager.GetString("EvadeAttack4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;giveup&quot;&gt;&lt;span class=&quot;char&quot;&gt;{0}&lt;/span&gt; faller ihop till marken av trötthet!&lt;/div&gt;.
        /// </summary>
        internal static string GiveUpStanimaString {
            get {
                return ResourceManager.GetString("GiveUpStanimaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;giveup&quot;&gt;&lt;span class=&quot;char&quot;&gt;{0}&lt;/span&gt; väljer att ge upp striden!&lt;/div&gt;.
        /// </summary>
        internal static string GiveUpString {
            get {
                return ResourceManager.GetString("GiveUpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;attack&quot;&gt;&lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; riktar ett hårt slag i &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt;s riktning, .
        /// </summary>
        internal static string HeavyAttack1 {
            get {
                return ResourceManager.GetString("HeavyAttack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;attack&quot;&gt;&lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; tar i från tåna och försöker träffa &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt;, .
        /// </summary>
        internal static string HeavyAttack2 {
            get {
                return ResourceManager.GetString("HeavyAttack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;attack&quot;&gt;&lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; samlar all sin kraft och slår mot &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt;, .
        /// </summary>
        internal static string HeavyAttack3 {
            get {
                return ResourceManager.GetString("HeavyAttack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;attack&quot;&gt;&lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; ger i från sig ett vrål och attackerar &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt;, .
        /// </summary>
        internal static string HeavyAttack4 {
            get {
                return ResourceManager.GetString("HeavyAttack4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to väldigt lätt.
        /// </summary>
        internal static string HitSeverity1 {
            get {
                return ResourceManager.GetString("HitSeverity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lätt.
        /// </summary>
        internal static string HitSeverity2 {
            get {
                return ResourceManager.GetString("HitSeverity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hårt.
        /// </summary>
        internal static string HitSeverity3 {
            get {
                return ResourceManager.GetString("HitSeverity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to väldigt hårt.
        /// </summary>
        internal static string HitSeverity4 {
            get {
                return ResourceManager.GetString("HitSeverity4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dödligt hårt.
        /// </summary>
        internal static string HitSeverity5 {
            get {
                return ResourceManager.GetString("HitSeverity5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;attack&quot;&gt;Med lätta steg riktar &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; en kvick attack mot &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt;, .
        /// </summary>
        internal static string LightAttack1 {
            get {
                return ResourceManager.GetString("LightAttack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;attack&quot;&gt;&lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; riktar ett snabbt slag mot &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt;, .
        /// </summary>
        internal static string LightAttack2 {
            get {
                return ResourceManager.GetString("LightAttack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;attack&quot;&gt;&lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; blir förvånad när &lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt;s attack dyker upp från ingenstans, .
        /// </summary>
        internal static string LightAttack3 {
            get {
                return ResourceManager.GetString("LightAttack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;attack&quot;&gt;&lt;span class=&quot;attacker&quot;&gt;{0}&lt;/span&gt; attackerar &lt;span class=&quot;defender&quot;&gt;{1}&lt;/span&gt; så snabbt att det knappt syns, .
        /// </summary>
        internal static string LightAttack4 {
            get {
                return ResourceManager.GetString("LightAttack4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;turn&quot;&gt;Runda {0}&lt;/div&gt;.
        /// </summary>
        internal static string NewTurn {
            get {
                return ResourceManager.GetString("NewTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;endresult&quot;&gt;Som det enda lag där en kombattant inte gett upp, står lag {0} som vinnare! Kombattanterna i laget får vardera {1} guldmynt som belöning!&lt;/div&gt;.
        /// </summary>
        internal static string WinString {
            get {
                return ResourceManager.GetString("WinString", resourceCulture);
            }
        }
    }
}
